yarnPath: ".yarn/releases/yarn-3.2.0.cjs"
nodeLinker: "node-modules"


npmAuthToken: "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"
npmPublishAccess: "public"
npmPublishRegistry: "https://registry.npmjs.org"
