name: 自动发布
on:
  push:
    tags:
      - release-**


jobs:
  npm-publish:
    name: 发布到NPM
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: package信息
        run: |
          echo "Release tag: ${GITHUB_REF_NAME}"
          echo "当前版本: $(git log -1 --format='%H')"
      - name: Publish
        run: RELEASE_TAG=${GITHUB_REF_NAME} make npm-publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
