name: 自动发布
on:
  push:
    tags:
      - release-**


jobs:
  npm-publish:
    name: 发布到NPM
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
      - name: publish
        run: |
          echo "latest-commit: $(git log)"
          RELEASE_TAG=${GITHUB_REF_NAME} make npm-publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
