name: Auto Release
on:
  push:
    tags:
      - release-**


jobs:
  npm-publish:
    name: 发布到NPM
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
      - name: publish
        run: |
          echo "latest-commit: $(git log)"
          make npm-publish tag=${GITHUB_REF_NAME}
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
