name: Manual Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 包的名称 package.json.name
        type: string
        required: true
        default: "@daifee/"
      version:
        description: 包的新版本号 package.json.version
        type: string
        default: "0.0.0"
        required: true

env:
  # 标签包含了「名称」、「版本」信息：@daifee/linked-list@0.0.0
  GIT_TAG: "${{ github.event.inputs.name }}@${{ github.event.inputs.version }}"
  GIT_BRANCH: release-${GIT_TAG}

jobs:
  update-package-version:
    name: 更新版本号
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3
      - name: 更新 package.version
        run: |
          make update-package-version tag=${GIT_TAG}
      - name: 查看文件变更
        run: git status
      - name: 提交代码
        run: |
          git config user.name "robot"
          git config user.email "robot@daifee.com"
          git add --all
          git commit -m "${GIT_TAG}"
          git tag ${GIT_TAG}
      - name: 推送到Github
        run: |
          echo ${GIT_BRANCH}

  npm-publish:
    name: 发布到NPM
    runs-on: ubuntu-latest
    needs: update-package-version
    steps:
      - name: 检出
        uses: actions/checkout@v3
      - name: publish
        run: |
          git fetch --all --tags --prune
          git checkout tags/${{ needs.update-package-version.outputs.git_tag }} -b tempbanch
          echo "latest-commit-id: $(git log)"
          make npm-publish tag=${{ needs.update-package-version.outputs.git_tag }}
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
