name: 手动发布

on:
  workflow_dispatch:
    inputs:
      name:
        description: 包的名称 package.json.name
        type: string
        required: true
        default: "@daifee/"
      version:
        description: 包的新版本号 package.json.version
        type: string
        default: "0.0.0"
        required: true

env:
  # 标签包含了「名称」、「版本」信息：@daifee/linked-list@0.0.0
  RELEASE_TAG: "release-${{ github.event.inputs.name }}@${{ github.event.inputs.version }}"
  RELEASE_BRANCH: "release/temp/${{ github.event.inputs.name }}@${{ github.event.inputs.version }}"

jobs:
  update-package-version:
    name: 更新版本号
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 更新 package.version
        run: |
          RELEASE_TAG=${RELEASE_TAG} make update-package-version
      - name: 查看文件变更
        run: git status
      - name: 提交代码
        run: |
          git config user.name "robot"
          git config user.email "robot@daifee.com"
          git add --all
          git commit -m "${RELEASE_TAG}"
          git tag ${RELEASE_TAG}
      - name: 推送到Github
        run: |
          echo ${RELEASE_BRANCH}
          git push origin HEAD:${RELEASE_BRANCH} --follow-tags

  npm-publish:
    name: 发布到NPM
    runs-on: ubuntu-latest
    needs: update-package-version
    if: needs.update-package-version.result == 'success'
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 检出分支
        run: git checkout ${RELEASE_BRANCH}
      - name: Publish
        run: |
          echo "latest-commit: $(git log)"
          RELEASE_TAG=${RELEASE_TAG} make npm-publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
