name: Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: 包名称
        type: string
        required: true
        default: "@daifee"
      version:
        description: 新版本号
        type: string
        required: true

jobs:
  package-version:
    name: 更新版本号
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3
      - name: 设置git用户
        run: |
          git config user.name "robot"
          git config user.email "robot@daifee.com"
      - name: 更新 package.version
        run: make new-version name=${{ github.event.inputs.name }} version=${{ github.event.inputs.version }}
      - name: 提交代码
        run: |
          git add --all
          git commit -m "release-${{ github.event.inputs.name }}-${{ github.event.inputs.version }}"
          git tag "release-${{ github.event.inputs.name }}-${{ github.event.inputs.version }}"
          git push
