name: Release
on:
  push:
    tags: ["release-*"]

jobs:
  log-changes:
    name: 记录变更文件
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v2
      - name: 列出变更文件
        run: git diff --name-only HEAD^..HEAD
      - name: 输出 tag name
        run: echo ${{ GITHUB_REF_NAME }}
