name: Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: 包名称
        type: string
        required: true
        default: "@daifee"
      version:
        description: 新版本号
        type: string
        required: true

jobs:
  log-changes:
    name: 记录变更文件
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v2
      - name: 列出变更文件
        run: git diff --name-only HEAD^..HEAD

  update-version:
    name: 更新版本号
    runs-on: ubuntu-latest
    needs: log-changes
    steps:
      - name: 检出
        uses: actions/checkout@v3
      - name: 设置git用户
        run: |
          git config user.name "robot"
          git config user.email "robot@daifee.com"
      - name: 更新 package.version
        run: make new-version name=${{ github.event.inputs.name }} version=${{ github.event.inputs.version }}
      - name: 提交代码
        run: |
          git add --all
          git commit -m "release-${{ github.event.inputs.name }}-${{ github.event.inputs.version }}"
          git tag "release-${{ github.event.inputs.name }}-${{ github.event.inputs.version }}"
          git push --tags
  npm-release:
    name: 发布到NPM
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: build and test
        run: make pre-publish
      - name: publish
        run: make npm-publish
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
